### ISSUE TITLE
Is `oauth2_access_token_url` standard LTI2 payload?

### ISSUE THREAD

**Issue by randomor** [instructure/lti2_reference_tool_provider#23]
I see `params['oauth2_access_token_url']` as part of the registration payload. https://github.com/instructure/lti2_reference_tool_provider/blob/master/app/lti_controller.rb#L46

However, in current version Canvas LMS, there is no such parameter posted to the tool registration endpoint. Is there a story here? 

BTW, is LTI2 tool registration flow still the recommended process for building Canvas LTI tools? My sense with this discussion is that the standard is changing too much and the dev is on pause: https://community.canvaslms.com/docs/DOC-2040

**Comment by abutterf** [comment]
That param only gets sent if a feature flag is enabled via account settings.

As far as our implementation of the LTI 2 platform, it is under active development. We do have tool providers building on top of it but it has not yet reached feature parity with our LTI 1 platform. That being said, once it is finished, it will allow some pretty awesome integrations with Canvas that LTI 1 is simply unable to deliver.

**Comment by randomor** [comment]
Thanks for the info! Where can I find the most up-to-date documentation regarding LTI 2 support in Canvas other than IMS Spec doc?

**Comment by abutterf** [comment]
At the moment the IMS spec is probably the best documentation to look at. Once you have a tool that can go through the registration process you will be able to see all of the capabilities and services Canvas currently supports in the tool consumer profile you get back during that process.
